packages:
  - 'libs/*/*'

allowBuilds:
  '@parcel/watcher': false
  '@percy/core': true
  '@prisma/client': true
  '@swc/core': false
  cpu-features: false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  playwright-chromium: true
  protobufjs: false
  ssh2: false
  unrs-resolver: false
