import Fastify from 'fastify';
import compress from '@fastify/compress';
import { app } from './app/app';

const host = process.env.HOST ?? 'localhost';
const port = process.env.PORT
  ? Number(process.env.PORT)
  : process.env.AEP_API_GATEWAY_PORT
    ? Number(process.env.AEP_API_GATEWAY_PORT)
    : 46000;

const isProduction = process.env.NODE_ENV === 'production';

// Instantiate Fastify with some config
const server = Fastify({
  logger: {
    level: isProduction ? 'info' : 'debug',
    ...(isProduction
      ? {
          // Production logging format
          serializers: {
            req(req) {
              return {
                method: req.method,
                url: req.url,
                hostname: req.hostname,
                remoteAddress: req.ip,
              };
            },
            res(res) {
              return {
                statusCode: res.statusCode,
              };
            },
          },
        }
      : {
          // Development logging format
          transport: {
            target: 'pino-pretty',
            options: {
              translateTime: 'HH:MM:ss Z',
              ignore: 'pid,hostname',
            },
          },
        }),
  },
  pluginTimeout: 20000, // Increase plugin timeout to 20 seconds for debugging
  trustProxy: true, // Trust proxy headers for accurate IP detection
  requestIdLogLabel: 'reqId',
  disableRequestLogging: false,
  requestIdHeader: 'x-request-id',
});

// ============================================================================
// Compression Plugin
// ============================================================================
// Register compression before other plugins for optimal performance
server.register(compress, {
  global: true,
  threshold: 1024, // Compress responses larger than 1KB
  encodings: ['gzip', 'deflate'],
  // Customize compression per content type
  customTypes: /^text\/|^application\/json|^application\/javascript/,
  // Don't compress already compressed formats
  removeContentLengthHeader: true,
});

// ============================================================================
// Caching Headers Hook
// ============================================================================
server.addHook('onSend', async (request, reply) => {
  // Skip caching headers for non-GET requests
  if (request.method !== 'GET') {
    return;
  }

  const url = request.url;

  // Static assets - aggressive caching
  if (url.match(/\.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$/)) {
    reply.header('Cache-Control', 'public, max-age=31536000, immutable');
    reply.header('Expires', new Date(Date.now() + 31536000000).toUTCString());
    return;
  }

  // API responses - short-term caching with validation
  if (url.startsWith('/api/')) {
    // Different caching strategies based on endpoint
    if (url.includes('/health') || url.includes('/metrics')) {
      // Health checks - no cache
      reply.header('Cache-Control', 'no-cache, no-store, must-revalidate');
      reply.header('Pragma', 'no-cache');
      reply.header('Expires', '0');
    } else if (url.includes('/auth') || url.includes('/user')) {
      // Auth/user endpoints - no cache for security
      reply.header('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
      reply.header('Pragma', 'no-cache');
      reply.header('Expires', '0');
    } else if (url.match(/\/api\/(projects|templates|widgets)/)) {
      // Data endpoints - short cache with revalidation
      reply.header('Cache-Control', 'private, max-age=60, must-revalidate');
      reply.header('Vary', 'Authorization, Accept-Encoding');
    } else {
      // Default API caching
      reply.header('Cache-Control', 'private, max-age=300');
      reply.header('Vary', 'Authorization, Accept-Encoding');
    }
  } else {
    // HTML pages - moderate caching with validation
    reply.header('Cache-Control', 'public, max-age=3600, must-revalidate');
    reply.header('Vary', 'Accept-Encoding');
  }

  // Add ETag support for conditional requests
  if (reply.statusCode === 200 && !reply.getHeader('etag')) {
    // ETag will be automatically generated by Fastify for JSON responses
  }
});

// ============================================================================
// Performance Headers Hook
// ============================================================================
server.addHook('onSend', async (request, reply) => {
  // Add Server-Timing header for performance monitoring
  const responseTime = reply.getResponseTime();
  reply.header('Server-Timing', `total;dur=${responseTime.toFixed(2)}`);

  // Add custom performance headers
  reply.header('X-Response-Time', `${responseTime.toFixed(2)}ms`);
});

// ============================================================================
// Request Deduplication (Optional)
// ============================================================================
// Simple in-memory cache for GET request deduplication
const pendingRequests = new Map<string, Promise<any>>();

server.addHook('onRequest', async (request, reply) => {
  // Only deduplicate GET requests
  if (request.method !== 'GET') {
    return;
  }

  // Create a cache key from URL and headers
  const cacheKey = `${request.url}:${request.headers.authorization || ''}`;

  // Check if there's already a pending request
  const pending = pendingRequests.get(cacheKey);
  if (pending) {
    // Wait for the pending request to complete
    try {
      const result = await pending;
      reply.send(result);
      return reply;
    } catch (error) {
      // If the pending request failed, continue with this request
    }
  }
});

// ============================================================================
// Error Handling
// ============================================================================
server.setErrorHandler((error, request, reply) => {
  // Log error
  request.log.error({
    err: error,
    url: request.url,
    method: request.method,
  }, 'Request error');

  // Production error response (hide internal details)
  if (isProduction) {
    const statusCode = (error as any).statusCode || 500;
    reply.code(statusCode).send({
      statusCode,
      error: statusCode >= 500 ? 'Internal Server Error' : error.name,
      message: statusCode >= 500 ? 'An unexpected error occurred' : error.message,
    });
  } else {
    // Development error response (show details)
    const statusCode = (error as any).statusCode || 500;
    reply.code(statusCode).send({
      statusCode,
      error: error.name,
      message: error.message,
      stack: error.stack,
    });
  }
});

// ============================================================================
// 404 Handler
// ============================================================================
server.setNotFoundHandler((request, reply) => {
  reply.code(404).send({
    statusCode: 404,
    error: 'Not Found',
    message: `Route ${request.method}:${request.url} not found`,
  });
});

// Register your application as a normal plugin.
server.register(app);

// ============================================================================
// Graceful Shutdown
// ============================================================================
const signals = ['SIGINT', 'SIGTERM'];

signals.forEach((signal) => {
  process.on(signal, async () => {
    server.log.info(`Received ${signal}, shutting down gracefully...`);

    try {
      await server.close();
      server.log.info('Server closed successfully');
      process.exit(0);
    } catch (err) {
      server.log.error({ err }, 'Error during shutdown');
      process.exit(1);
    }
  });
});

// Handle uncaught errors
process.on('uncaughtException', (err) => {
  server.log.fatal({ err }, 'Uncaught exception');
  process.exit(1);
});

process.on('unhandledRejection', (err) => {
  server.log.fatal({ err }, 'Unhandled rejection');
  process.exit(1);
});

// Start listening.
server.listen({ port, host }, (err) => {
  if (err) {
    server.log.error(err);
    process.exit(1);
  } else {
    console.log(`[ ready ] http://${host}:${port}`);
    server.log.info(`Server listening on http://${host}:${port}`);
    server.log.info(`Environment: ${process.env.NODE_ENV || 'development'}`);
  }
});
