apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${GRAFANA_INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: ${GRAFANA_INFLUXDB_ORG}
      defaultBucket: ${GRAFANA_INFLUXDB_BUCKET}
    secureJsonData:
      token: ${GRAFANA_INFLUXDB_TOKEN}
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: ${GRAFANA_POSTGRES_URL}
    user: ${GRAFANA_POSTGRES_USER}
    jsonData:
      database: ${GRAFANA_POSTGRES_DB}
      sslmode: disable
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    editable: true
